//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS_Agents
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Agents
    {
        public int ID { get; set; }
        public Nullable<int> ID_Agent { get; set; }
        public string Name { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Type { get; set; }
    }
}
