//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS_Agents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user1Entities : DbContext
    {
        private static user1Entities _context;

        public static user1Entities GetContext()
        {
            if (_context == null)
            {
                _context = new user1Entities();
            }
            return _context;
        }
        public user1Entities()
            : base("name=user1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<History_Agents> History_Agents { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Productsale> Productsales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeAgent> TypeAgents { get; set; }
        public virtual DbSet<TypeProduct> TypeProducts { get; set; }
    }
}
